# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Grafiki/LinGraph.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1015, 764)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 69, 991, 461))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(410, 20, 201, 61))
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(240, 600, 201, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(600, 600, 201, 16))
        self.label_3.setObjectName("label_3")
        self.yInput = QtWidgets.QLineEdit(Form)
        self.yInput.setGeometry(QtCore.QRect(650, 630, 113, 20))
        self.yInput.setObjectName("yInput")
        self.xInput = QtWidgets.QLineEdit(Form)
        self.xInput.setGeometry(QtCore.QRect(280, 630, 113, 20))
        self.xInput.setObjectName("xInput")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(390, 670, 251, 71))
        self.pushButton.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Линейный график"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Tab 2"))
        self.label.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Составление графика</span></p></body></html>"))
        self.label.setText(_translate("Form", "Составление графика"))
        self.label_2.setText(_translate("Form", "Введите через запятую значения оси X"))
        self.label_3.setText(_translate("Form", "Введите через запятую значения оси Y"))
        self.pushButton.setText(_translate("Form", "Рассчитать"))
