# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 400)
        Dialog.setStyleSheet("background-color: rgb(100, 100, 100);")
        self.LabelLogin = QtWidgets.QLabel(Dialog)
        self.LabelLogin.setGeometry(QtCore.QRect(140, 110, 71, 41))
        self.LabelLogin.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"")
        self.LabelLogin.setObjectName("LabelLogin")
        self.LabelParol = QtWidgets.QLabel(Dialog)
        self.LabelParol.setGeometry(QtCore.QRect(130, 210, 71, 31))
        self.LabelParol.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"")
        self.LabelParol.setObjectName("LabelParol")
        self.loginText = QtWidgets.QLineEdit(Dialog)
        self.loginText.setGeometry(QtCore.QRect(240, 120, 131, 31))
        self.loginText.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.loginText.setObjectName("loginText")
        self.ParolText = QtWidgets.QLineEdit(Dialog)
        self.ParolText.setGeometry(QtCore.QRect(240, 210, 131, 31))
        self.ParolText.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.ParolText.setObjectName("ParolText")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(170, 40, 151, 31))
        self.label.setStyleSheet("font: 75 italic 18pt \"Segoe UI\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.label.setObjectName("label")
        self.vvod = QtWidgets.QPushButton(Dialog)
        self.vvod.setGeometry(QtCore.QRect(190, 290, 101, 31))
        self.vvod.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(49, 49, 49);\n"
"font: 15pt \"MS Shell Dlg 2\";")
        self.vvod.setObjectName("vvod")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.LabelLogin.setText(_translate("Dialog", "Логин"))
        self.LabelParol.setText(_translate("Dialog", "Пароль"))
        self.label.setText(_translate("Dialog", "Авторизация"))
        self.vvod.setText(_translate("Dialog", "Войти"))


